name: MR_WorkflowDispatch

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted]
    #runs-on: ubuntu-latest
    timeout-minutes: 240
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install pre-req for build
        run: sudo apt -y install sudo build-essential libtool autotools-dev automake pkg-config libssl-dev libevent-dev bsdmainutils libboost-all-dev libdb-dev libdb++-dev

      - name: Build
        run: |
          ./autogen.sh; mkdir build; cd build; ../configure; make -j24

      - name: Static code analysis
        uses: deep5050/cppcheck-action@main
        with:
          enable:
          inconclusive:
          force:
          std: c++20

