name: WorkflowTest

on:
  push:
    branches:
      - '!mydev'
      - SVN-2434_unique_ptr_zero_len_array
      - SVN-2449_cmake_debug_enable
      - 'SVN-24**'
  repository_dispatch:
    types: [run_branch]

jobs:
  build-and-unit-test:
    runs-on: [self-hosted]
    # runs-on: ubuntu-latest
    # runs-on: ubuntu-20.04
    timeout-minutes: 240
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Logging branch
        run: |
          echo "If running here through the external signal..."
          echo "branch: ${{ github.event.client_payload.branch }}"
          echo "Checking the branch being worked..."
          git status
      - name: Install pre-req for build
        run: >
          sudo apt -y install build-essential libtool autotools-dev automake pkg-config libssl-dev libevent-dev bsdmainutils libboost-all-dev libdb-dev libdb++-dev
      - name: Build
        run: |
          ./autogen.sh; 
          mkdir build; 
          cd build; 
          ../configure --enable-debug; 
          make -j24
      - name: Unit test
        run: |
          cd build; 
          ./src/test/test_bitcoin
  build-and-functional-test:
    runs-on: [self-hosted]
    # runs-on: ubuntu-latest
    # runs-on: ubuntu-20.04
    timeout-minutes: 200
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install pre-req for build
        run: >
          sudo apt -y install build-essential libtool autotools-dev automake pkg-config libssl-dev libevent-dev bsdmainutils libboost-all-dev libdb-dev libdb++-dev
      - name: Build
        run: |
          ./autogen.sh; 
          mkdir build; 
          cd build; 
          ../configure --enable-debug; 
          make -j24
      - name: Install pre-req for functional test
        run: | 
          sudo apt -y install pip; 
          pip install ecdsa bip32utils
      - name: Functional test
        run: |
          cd build; 
          ./test/functional/test_runner.py --timeout-factors=4
