name: WorkflowTest

on:
  push:
    branches:
      - mydev

jobs:
  build:
    runs-on: [self-hosted]
    timeout-minutes: 120
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install pre-req
        run: sudo apt-get -y install build-essential libtool autotools-dev automake pkg-config libssl-dev libevent-dev bsdmainutils libboost-all-dev libdb-dev libdb++-dev
      - name: Build and Test
        run: |
          # Add your build and test commands here
          # sudo apt-get update && sudo apt-get -y install build-essential libtool autotools-dev automake pkg-config libssl-dev libevent-dev bsdmainutils libboost-all-dev libdb-dev libdb++-dev; 
          cd /home/runner/work/bitcoin-sv/bitcoin-sv; git checkout mydev; ./autogen.sh; mkdir build; cd build; ../configure; make -j12 
