name: WorkflowTest

on:
  push:
    branches:
      - mydev

jobs:
  build-and-unit-test:
    # runs-on: [self-hosted]
    runs-on: ubuntu-latest
    # runs-on: ubuntu-20.04
    timeout-minutes: 200
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install pre-req for build
        run: >
          sudo apt -y install build-essential libtool autotools-dev automake pkg-config libssl-dev libevent-dev bsdmainutils libboost-all-dev libdb-dev libdb++-dev
      - name: Build
        run: |
          ./autogen.sh; 
          mkdir build; 
          cd build; 
          ../configure --enable-debug; 
          make -j24
      - name: Unit test
        run: |
          cd build; 
          ./src/test/test_bitcoin
  build-and-functional-test:
    runs-on: [self-hosted]
    # runs-on: ubuntu-latest
    # runs-on: ubuntu-20.04
    timeout-minutes: 200
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install pre-req for build
        run: >
          sudo apt -y install build-essential libtool autotools-dev automake pkg-config libssl-dev libevent-dev bsdmainutils libboost-all-dev libdb-dev libdb++-dev
      - name: Build
        run: |
          ./autogen.sh; 
          mkdir build; 
          cd build; 
          ../configure --enable-debug; 
          make -j24
      - name: Install pre-req for functional test
        run: | 
          sudo apt -y install pip; 
          pip install ecdsa bip32utils
      - name: Functional test
        run: |
          cd build; 
          ./test/functional/test_runner.py --timeout-factors=4
