name: WorkflowTest

on:
  push:
    branches:
      - mydev

jobs:
  build:
    runs-on: [self-hosted]
    timeout-minutes: 120
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install pre-req
        # run: apt -y install sudo git build-essential libtool autotools-dev automake pkg-config libssl-dev libevent-dev bsdmainutils libboost-all-dev libdb-dev libdb++-dev
        run: apt -y install sudo build-essential libtool autotools-dev automake pkg-config libssl-dev libevent-dev bsdmainutils libboost-all-dev libdb-dev libdb++-dev
      - name: Build and Test
        run: |
          #echo "not this time..."
          #pwd
          #git branch
          #cd /actions-runner/_work/bitcoin-sv/bitcoin-sv && git checkout mydev; ./autogen.sh; mkdir build; cd build; ../configure; make -j24
          ./autogen.sh; mkdir build; cd build; ../configure; make -j24
      - name: linking bsv
        run: |
          ln -f -s /actions-runner/_work/bitcoin-sv/bitcoin-sv/build/src/bitcoind /usr/local/bin/bitcoind; ln -f -s /actions-runner/_work/bitcoin-sv/bitcoin-sv/build/src/bitcoin-cli /usr/local/bin/bitcoin-cli;
      - name: functional tests
        run: |
          cd /actions-runner/_work/bitcoin-sv/bitcoin-sv/build && ./src/test/test_bitcoin
